changelog:
  categories:
  - title: Changes
    labels:
    - '*'
    exclude:
      labels:
      - dependencies
  - title: Dependencies
    labels:
    - dependencies

# see https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#creating-automatically-generated-release-notes-for-a-new-release
